export const xd = {
	// rest: [
	// 	'people-holding-hands',
	// 	'people-hugging',
	// 	'people-with-bunny-ears',
	// 	'people-wrestling',

	// 	'multiply',

	// 	'musical-keyboard',
	// 	'musical-note',
	// 	'musical-notes',
	// 	'musical-score',
	// 	'muted-speaker',
	// 	'mx-claus',
	// 	'nail-polish',
	// 	'name-badge',
	// 	'national-park',
	// 	'necktie',
	// 	'nest-with-eggs',
	// 	'night-with-stars',
	// 	'nine-thirty',
	// 	'ninja',
	// 	'non-potable-water',
	// 	'nose',

	// 	'oden',
	// 	'office-building',
	// 	'office-worker',
	// 	'olive',
	// 	'om',
	// 	'oncoming-automobile',
	// 	'oncoming-bus',
	// 	'oncoming-fist',

	// 	'oncoming-police-car',
	// 	'oncoming-taxi',

	// 	'one-piece-swimsuit',
	// 	'one-thirty',

	// 	'open-hands',

	// 	'ophiuchus',

	// 	'orthodox-cross',

	// 	'outbox-tray',
	// 	'parachute',

	// 	'pilot',

	// 	'package',

	// 	'palms-up-together',

	// 	'part-alternation-mark',

	// 	'passenger-ship',
	// 	'passport-control',

	// 	'paw-prints',
	// 	'peace-symbol',

	// 	'pen',

	// 	'performing-arts',

	// 	'pi-ata',
	// 	'pick',
	// 	'pickup-truck',

	// 	'pine-decoration',
	// 	'ping-pong',

	// 	'pisces',

	// 	'place-of-worship',

	// 	'playground-slide',

	// 	'plus',
	// 	'police-car',
	// 	'police-car-light',
	// 	'police-officer',

	// 	'poodle',
	// 	'pool-8-ball',
	// 	'post-office',
	// 	'pot-of-food',

	// 	'potted-plant',
	// 	'poultry-leg',
	// 	'pouring-liquid',

	// 	'prince',

	// 	'prohibited',

	// 	'purple-square',
	// 	'purse',
	// 	'pushpin',
	// 	'puzzle-piece',

	// 	'rabbit',
	// 	'owl',
	// 	'parrot',
	// 	'panda',
	// 	'peach',
	// 	'penguin',
	// 	'pig-nose',
	// 	'pig',
	// 	'palm-tree',
	// 	'raccoon',
	// 	'peacock',
	// 	'rat',
	// 	'rooster',
	// 	'scorpion',
	// 	'rose',
	// 	'otter',
	// 	'rhinoceros',
	// 	'ox',
	// 	'mushroom',
	// 	'orangutan',
	// 	'polar-bear',
	// 	'whale',
	// 	'two-hump-camel',
	// 	'spouting-whale',
	// 	'squid',
	// 	'spider',
	// 	'spider-web',
	// 	'snail',
	// 	'turkey',
	// 	'turtle',
	// 	'tulip',
	// 	'snake',
	// 	'skunk',
	// 	'shrimp',
	// 	'seal',
	// 	'service-dog',
	// 	'octopus',

	// 	'potato',
	// 	'pretzel',

	// 	'racing-car',

	// 	'radioactive',
	// 	'railway-car',
	// 	'railway-track',
	// 	'rainbow',

	// 	'raised-fist',

	// 	'raising-hands',
	// 	'ram',

	// 	'recycling-symbol',
	// 	'red-apple',

	// 	'red-exclamation-mark',
	// 	'red-hair',

	// 	'red-question-mark',
	// 	'red-square',
	// 	'red-triangle-pointed-down',
	// 	'red-triangle-pointed-up',

	// 	'registered',

	// 	'reminder-ribbon',

	// 	'rescue-worker-s-helmet',
	// 	'restroom',

	// 	'rice-ball',
	// 	'rice-cracker',

	// 	'ring',
	// 	'ring-buoy',
	// 	'ringed-planet',
	// 	'roasted-sweet-potato',
	// 	'rock',
	// 	'rocket',

	// 	'roller-coaster',
	// 	'roller-skate',

	// 	'rosette',
	// 	'rugby-football',
	// 	'running-shirt',
	// 	'running-shoe',

	// 	'safety-vest',
	// 	'sagittarius',
	// 	'sailboat',
	// 	'sake',
	// 	'salt',
	// 	'sandwich',

	// 	'sari',

	// 	'sauropod',
	// 	'saxophone',
	// 	'scarf',
	// 	'school',
	// 	'scientist',

	// 	'scorpio',
	// 	'scroll',
	// 	'seat',
	// 	'see-no-evil-monkey',
	// 	'seedling',

	// 	'seven-thirty',

	// 	'shallow-pan-of-food',
	// 	'shamrock',
	// 	'shark',
	// 	'shaved-ice',
	// 	'sheaf-of-rice',
	// 	'shibuya',
	// 	'shinto-shrine',
	// 	'ship',
	// 	'shooting-star',

	// 	'shortcake',
	// 	'shorts',

	// 	'six-thirty',
	// 	'skateboard',
	// 	'skier',
	// 	'skis',

	// 	'sled',

	// 	'slot-machine',
	// 	'sloth',
	// 	'small-airplane',
	// 	'small-blue-diamond',
	// 	'small-orange-diamond',

	// 	'snow-capped-mountain',
	// 	'snowboarder',
	// 	'snowflake',
	// 	'snowman',
	// 	'snowman-without-snow',

	// 	'soccer-ball',
	// 	'socks',
	// 	'soft-ice-cream',
	// 	'softball',

	// 	'spade-suit',
	// 	'spaghetti',
	// 	'sparkle',
	// 	'sparkler',
	// 	'sparkles',

	// 	'speak-no-evil-monkey',
	// 	'speaker-high-volume',
	// 	'speaker-low-volume',
	// 	'speaker-medium-volume',
	// 	'speaking-head',

	// 	'speedboat',

	// 	'spiral-shell',

	// 	'spoon',
	// 	'sport-utility-vehicle',
	// 	'sports-medal',

	// 	'stadium',
	// 	'star',
	// 	'star-and-crescent',
	// 	'star-of-david',
	// 	'station',
	// 	'statue-of-liberty',
	// 	'steaming-bowl',

	// 	'strawberry',
	// 	'student',

	// 	'stuffed-flatbread',
	// 	'sun',
	// 	'sun-behind-cloud',
	// 	'sun-behind-large-cloud',
	// 	'sun-behind-rain-cloud',
	// 	'sun-behind-small-cloud',

	// 	'sunflower',
	// 	'sunglasses',
	// 	'sunrise',
	// 	'sunrise-over-mountains',
	// 	'sunset',
	// 	'superhero',

	// 	'sushi',
	// 	'suspension-railway',
	// 	'swan',
	// 	'sweat-droplets',
	// 	'synagogue',

	// 	't-rex',
	// 	't-shirt',
	// 	'taco',
	// 	'takeout-box',
	// 	'tamale',
	// 	'tanabata-tree',
	// 	'tangerine',
	// 	'taurus',
	// 	'taxi',

	// 	'teacup-without-handle',
	// 	'teapot',

	// 	'technologist',

	// 	'ten-thirty',
	// 	'tennis',
	// 	'tent',

	// 	'thong-sandal',

	// 	'three-thirty',

	// 	'ticket',
	// 	'tiger',

	// 	'tokyo-tower',
	// 	'tomato',
	// 	'tongue',

	// 	'tooth',

	// 	'top-hat',
	// 	'tornado',
	// 	'tractor',
	// 	'trade-mark',
	// 	'train',
	// 	'tram',
	// 	'tram-car',

	// 	'transgender-symbol',

	// 	'trident-emblem',
	// 	'troll',
	// 	'trolleybus',
	// 	'trophy',
	// 	'tropical-drink',
	// 	'tropical-fish',

	// 	'trumpet',
	// 	'tumbler-glass',

	// 	'twelve-thirty',

	// 	'watermelon',
	// 	'two-thirty',
	// 	'umbrella',

	// 	'umbrella-with-rain-drops',
	// 	'unicorn',

	// 	'vertical-traffic-light',
	// 	'vibration-mode',

	// 	'video-game',

	// 	'violin',
	// 	'virgo',
	// 	'volcano',
	// 	'volleyball',
	// 	'vulcan-salute',

	// 	'warning',

	// 	'water-buffalo',
	// 	'water-closet',
	// 	'water-wave',

	// 	'wavy-dash',

	// 	'wedding',

	// 	'wheel',
	// 	'wheel-of-dharma',
	// 	'wheelchair-symbol',

	// 	'white-exclamation-mark',

	// 	'white-hair',

	// 	'wilted-flower',

	// 	'wolf',

	// 	'women-s-room',
	// 	'women-with-bunny-ears',
	// 	'women-wrestling',
	// 	'wood',

	// 	'worm',

	// 	'x-ray',

	// 	'yin-yang',

	// 	'zebra',
	// 	'zombie',

	// 	'flamingo',

	// 	'flat-shoe',
	// 	'flatbread',
	// 	'fleur-de-lis',
	// 	'flexed-biceps',

	// 	'flower-playing-cards',

	// 	'fly',
	// 	'flying-disc',
	// 	'flying-saucer',
	// 	'fog',
	// 	'foggy',
	// 	'folded-hands',
	// 	'fondue',
	// 	'foot',
	// 	'footprints',
	// 	'fork-and-knife',
	// 	'fork-and-knife-with-plate',
	// 	'fortune-cookie',
	// 	'fountain',
	// 	'fountain-pen',
	// 	'four-leaf-clover',

	// 	'four-thirty',
	// 	'fox',

	// 	'french-fries',
	// 	'fried-shrimp',
	// 	'frog',
	// 	'front-facing-baby-chick',

	// 	'fuel-pump',

	// 	'game-die',

	// 	'gemini',
	// 	'genie',
	// 	'giraffe',

	// 	'glasses',
	// 	'globe-showing-americas',
	// 	'globe-showing-asia-australia',
	// 	'globe-showing-europe-africa',
	// 	'globe-with-meridians',
	// 	'gloves',
	// 	'glowing-star',
	// 	'goal-net',
	// 	'goat',
	// 	'goggles',
	// 	'gorilla',
	// 	'graduation-cap',
	// 	'grapes',
	// 	'green-apple',

	// 	'green-salad',

	// 	'guide-dog',
	// 	'guitar',

	// 	'hamster',

	// 	'handbag',

	// 	'hatching-chick',
	// 	'headphone',
	// 	'health-worker',

	// 	'hear-no-evil-monkey',
	// 	'heart-decoration',
	// 	'heart-exclamation',
	// 	'heart-hands',
	// 	'heart-on-fire',
	// 	'heart-suit',

	// 	'heart-with-ribbon',
	// 	'heavy-dollar-sign',
	// 	'heavy-equals-sign',
	// 	'hedgehog',
	// 	'helicopter',

	// 	'high-heeled-shoe',
	// 	'high-speed-train',
	// 	'high-voltage',
	// 	'hiking-boot',
	// 	'hindu-temple',
	// 	'hippopotamus',

	// 	'honey-pot',
	// 	'honeybee',

	// 	'horizontal-traffic-light',
	// 	'horse',
	// 	'horse-racing',

	// 	'hospital',

	// 	'hundred-points',
	// 	'anger-symbol',
	// 	'speech-balloon',
	// 	'eye-in-speech-bubble',
	// 	'left-speech-bubble',
	// 	'right-anger-bubble',
	// 	'thought-balloon',
	// 	'zzz',
	// 	'white-flower',
	// 	'hot-springs',
	// 	'stop-sign',

	// 	'hotel',

	// 	'house',
	// 	'house-with-garden',
	// 	'houses',
	// 	'hut',
	// 	'ice',
	// 	'ice-cream',
	// 	'ice-hockey',
	// 	'ice-skate',

	// 	'index-pointing-at-the-viewer',

	// 	'index-pointing-up',
	// 	'infinity',
	// 	'information',
	// 	'input-latin-letters',
	// 	'input-latin-lowercase',
	// 	'input-latin-uppercase',
	// 	'input-numbers',
	// 	'input-symbols',
	// 	'jack-o-lantern',
	// 	'japanese-castle',

	// 	'japanese-post-office',

	// 	'jar',
	// 	'jeans',
	// 	'joker',

	// 	'judge',
	// 	'kaaba',
	// 	'kangaroo',

	// 	'kick-scooter',
	// 	'kimono',

	// 	'koala',
	// 	'lab-coat',
	// 	'lacrosse',

	// 	'lady-beetle',
	// 	'large-blue-diamond',
	// 	'large-orange-diamond',

	// 	'latin-cross',
	// 	'leaf-fluttering-in-wind',
	// 	'leafy-green',

	// 	'lemon',
	// 	'leo',
	// 	'leopard',
	// 	'libra',

	// 	'light-rail',
	// 	'light-skin-tone',

	// 	'lion',
	// 	'lipstick',
	// 	'litter-in-bin-sign',
	// 	'lizard',
	// 	'llama',
	// 	'lobster',

	// 	'locomotive',
	// 	'lollipop',
	// 	'long-drum',

	// 	'lotus',

	// 	'loudspeaker',
	// 	'love-hotel',
	// 	'love-you-gesture',

	// 	'low-battery',

	// 	'left-luggage',

	// 	'lungs',
	// 	'mage',

	// 	'mahjong-red-dragon',
	// 	'male-sign',
	// 	'mammoth',

	// 	'map-of-japan',
	// 	'maple-leaf',
	// 	'martial-arts-uniform',
	// 	'mate',
	// 	'meat-on-bone',
	// 	'mechanic',

	// 	'medical-symbol',
	// 	'megaphone',
	// 	'melon',

	// 	'military-helmet',
	// 	'military-medal',
	// 	'milky-way',
	// 	'minibus',
	// 	'minus',

	// 	'mirror-ball',

	// 	'monkey',
	// 	'monorail',

	// 	'mosque',
	// 	'mosquito',
	// 	'motor-boat',
	// 	'motor-scooter',
	// 	'motorcycle',
	// 	'motorized-wheelchair',
	// 	'motorway',
	// 	'mount-fuji',
	// 	'mountain',
	// 	'mountain-cableway',
	// 	'mountain-railway',
	// 	'mouse',

	// 	'mouth',
	// 	'mrs-claus',
	// 	'ant',
	// 	'antenna-bars',
	// 	'aquarius',
	// 	'aries',
	// 	'articulated-lorry',

	// 	'artist-palette',
	// 	'astronaut',
	// 	'atm-sign',
	// 	'atom-symbol',
	// 	'auto-rickshaw',
	// 	'automobile',
	// 	'avocado',
	// 	'axe',

	// 	'baby-symbol',

	// 	'backpack',
	// 	'bacon',
	// 	'badger',
	// 	'badminton',

	// 	'baggage-claim',
	// 	'baguette-bread',

	// 	'bald',
	// 	'ballet-shoes',

	// 	'banana',
	// 	'bank',

	// 	'baseball',

	// 	'basketball',
	// 	'bat',

	// 	'beach-with-umbrella',
	// 	'beans',
	// 	'bear',

	// 	'beaver',

	// 	'beetle',
	// 	'bell',
	// 	'bell-pepper',
	// 	'bell-with-slash',

	// 	'bento-box',
	// 	'beverage-box',
	// 	'bicycle',
	// 	'bikini',
	// 	'billed-cap',
	// 	'biohazard',
	// 	'bird',
	// 	'birthday-cake',
	// 	'bison',
	// 	'biting-lip',

	// 	'black-nib',

	// 	'blossom',
	// 	'blowfish',

	// 	'blue-square',
	// 	'blueberries',
	// 	'boar',

	// 	'bone',

	// 	'bouquet',

	// 	'bowl-with-spoon',
	// 	'bowling',
	// 	'boxing-glove',
	// 	'brain',
	// 	'bread',
	// 	'breast-feeding',

	// 	'bridge-at-night',
	// 	'briefcase',
	// 	'briefs',

	// 	'bubble-tea',
	// 	'bubbles',

	// 	'bug',
	// 	'building-construction',
	// 	'bullet-train',
	// 	'bullseye',
	// 	'burrito',
	// 	'bus',
	// 	'bus-stop',
	// 	'bust-in-silhouette',
	// 	'busts-in-silhouette',
	// 	'butter',
	// 	'butterfly',
	// 	'cactus',

	// 	'camel',
	// 	'camera',
	// 	'camera-with-flash',
	// 	'camping',
	// 	'cancer',

	// 	'canoe',
	// 	'capricorn',

	// 	'carousel-horse',

	// 	'castle',

	// 	'check-box-with-check',
	// 	'check-mark',

	// 	'cherries',
	// 	'cherry-blossom',
	// 	'chess-pawn',

	// 	'children-crossing',
	// 	'chipmunk',
	// 	'chocolate-bar',
	// 	'chopsticks',
	// 	'christmas-tree',
	// 	'church',

	// 	'cinema',
	// 	'circled-m',
	// 	'circus-tent',
	// 	'cityscape',
	// 	'cityscape-at-dusk',

	// 	'clapper-board',

	// 	'classical-building',
	// 	'clinking-beer-mugs',
	// 	'clinking-glasses',

	// 	'closed-umbrella',
	// 	'cloud',
	// 	'cloud-with-lightning',
	// 	'cloud-with-lightning-and-rain',
	// 	'cloud-with-rain',
	// 	'cloud-with-snow',

	// 	'club-suit',
	// 	'clutch-bag',
	// 	'coat',
	// 	'cockroach',
	// 	'cocktail-glass',

	// 	'coffin',
	// 	'collision',
	// 	'comet',

	// 	'construction',

	// 	'convenience-store',
	// 	'cooked-rice',
	// 	'cookie',
	// 	'cooking',

	// 	'copyright',
	// 	'coral',

	// 	'cricket',
	// 	'cricket-game',

	// 	'cross-mark',

	// 	'crown',

	// 	'cucumber',
	// 	'cup-with-straw',
	// 	'cupcake',
	// 	'curling-stone',
	// 	'curly-hair',
	// 	'curly-loop',
	// 	'currency-exchange',
	// 	'curry-rice',
	// 	'custard',
	// 	'customs',
	// 	'cut-of-meat',
	// 	'cyclone',
	// 	'dango',
	// 	'dark-skin-tone',
	// 	'dashing-away',

	// 	'delivery-truck',
	// 	'department-store',
	// 	'derelict-house',
	// 	'desert',
	// 	'desert-island',

	// 	'diamond-suit',
	// 	'diamond-with-a-dot',

	// 	'divide',

	// 	'dizzy',

	// 	'dotted-six-pointed-star',
	// 	'double-curly-loop',
	// 	'double-exclamation-mark',
	// 	'doughnut',

	// 	'dress',

	// 	'droplet',
	// 	'drum',
	// 	'duck',
	// 	'dumpling',
	// 	'e-mail',
	// 	'eagle',
	// 	'ear',
	// 	'ear-of-corn',
	// 	'ear-with-hearing-aid',

	// 	'eight-pointed-star',
	// 	'eight-spoked-asterisk',
	// 	'eight-thirty',

	// 	'elephant',
	// 	'elevator',

	// 	'eleven-thirty',

	// 	'empty-nest',

	// 	'envelope',

	// 	'evergreen-tree',
	// 	'ewe',
	// 	'exclamation-question-mark',

	// 	'eye',

	// 	'eyes',

	// 	'factory',

	// 	'fairy',
	// 	'falafel',
	// 	'fallen-leaf',

	// 	'family',
	// 	'farmer',

	// 	'feather',
	// 	'female-sign',
	// 	'ferris-wheel',
	// 	'ferry',
	// 	'field-hockey',

	// 	'fire',
	// 	'fire-engine',

	// 	'fireworks',

	// 	'fish',
	// 	'fish-cake-with-swirl',
	// 	'fishing-pole',

	// 	'five-thirty',
	// 	'anchor',

	// 	'1st-place-medal',
	// 	'2nd-place-medal',
	// 	'3rd-place-medal',

	// 	'accordion',

	// 	'admission-tickets',
	// 	'aerial-tramway',
	// 	'airplane',
	// 	'airplane-arrival',
	// 	'airplane-departure',

	// 	'ambulance',
	// 	'american-football',
	// ],
	food: [
		'grapes',
		'melon',
		'watermelon',
		'tangerine',
		'lemon',
		'banana',
		'pineapple',
		'mango',
		'red-apple',
		'green-apple',
		'pear',
		'peach',
		'cherries',
		'strawberry',
		'kiwi-fruit',
		'tomato',
		'coconut',
		'avocado',
		'eggplant',
		'potato',
		'carrot',
		'ear-of-corn',
		'hot-pepper',
		'cucumber',
		'leafy green',
		'broccoli',
		'garlic',
		'onion',
		'mushroom',
		'peanuts',
		'chestnut',
		'bread',
		'croissant',
		'baguette bread',
		'pretzel',
		'bagel',
		'pancakes',
		'waffle',
		'cheese-wedge',
		'meat-on-bone',
		'poultry-leg',
		'cut-of-meat',
		'bacon',
		'hamburger',
		'french-fries',
		'pizza',
		'hot-dog',
		'sandwich',
		'taco',
		'burrito',
		'stuffed-flatbread',
		'falafel',
		'egg',
		'cooking',
		'shallow-pan-of-food',
		'pot-of-food',
		'bowl-with-spoon',
		'green-salad',
		'popcorn',
		'butter',
		'salt',
		'canned-food',
		'bento-box',
		'rice-cracker',
		'rice-ball',
		'cooked-rice',
		'curry-rice',
		'steaming-bowl',
		'spaghetti',
		'roasted-sweet-potato',
		'oden',
		'sushi',
		'fried-shrimp',
		'fish-cake-with-swirl',
		'moon-cake',
		'dango',
		'dumpling',
		'fortune-cookie',
		'takeout-box',
		'crab',
		'lobster',
		'shrimp',
		'squid',
		'oyster',
		'soft-ice-cream',
		'shaved-ice',
		'ice-cream',
		'doughnut',
		'cookie',
		'birthday-cake',
		'shortcake',
		'cupcake',
		'pie',
		'chocolate-bar',
		'candy',
		'lollipop',
		'custard',
		'honey-pot',
		'baby-bottle',
		'glass-of-milk',
		'hot-beverage',
		'teacup-without-handle',
		'sake',
		'bottle-with-popping-cork',
		'wine-glass',
		'cocktail-glass',
		'tropical-drink',
		'beer-mug',
		'clinking-beer-mugs',
		'clinking-glasses',
		'tumbler-glass',
		'cup-with-straw',
		'beverage-box',
		'mate',
		'ice',
		'chopsticks',
		'fork-and-knife-with-plate',
		'fork-and-knife',
		'spoon',
		'kitchen-knife',
		'amphora',
	],
	objects: [
		'glasses',
		'sunglasses',
		'goggles',
		'lab-coat',
		'safety-vest',
		'necktie',
		't-shirt',
		'jeans',
		'scarf',
		'gloves',
		'coat',
		'socks',
		'dress',
		'kimono',
		'sari',
		'one-piece-swimsuit',
		'briefs',
		'shorts',
		'bikini',
		'woman’s-clothes',
		'purse',
		'handbag',
		'clutch-bag',
		'shopping-bags',
		'backpack',
		'thong-sandal',
		'man’s-shoe',
		'running-shoe',
		'hiking-boot',
		'flat-shoe',
		'high-heeled-shoe',
		'woman’s-sandal',
		'ballet-shoes',
		'woman’s-boot',
		'crown',
		'woman’s-hat',
		'top-hat',
		'graduation-cap',
		'billed-cap',
		'rescue-worker’s-helmet',
		'prayer-beads',
		'lipstick',
		'ring',
		'gem-stone',
		'muted-speaker',
		'speaker-low-volume',
		'speaker-medium-volume',
		'speaker-high-volume',
		'loudspeaker',
		'megaphone',
		'postal-horn',
		'bell',
		'bell-with-slash',
		'musical-score',
		'musical-note',
		'musical-notes',
		'studio-microphone',
		'level-slider',
		'control-knobs',
		'microphone',
		'headphone',
		'radio',
		'saxophone',
		'guitar',
		'musical-keyboard',
		'trumpet',
		'violin',
		'banjo',
		'drum',
		'mobile-phone',
		'mobile-phone-with-arrow',
		'telephone',
		'telephone-receiver',
		'pager',
		'fax-machine',
		'battery',
		'electric-plug',
		'laptop',
		'desktop-computer',
		'printer',
		'keyboard',
		'computer-mouse',
		'trackball',
		'computer-disk',
		'floppy-disk',
		'optical-disk',
		'dvd',
		'abacus',
		'movie-camera',
		'film-frames',
		'film-projector',
		'clapper-board',
		'television',
		'camera',
		'camera-with-flash',
		'video-camera',
		'videocassette',
		'magnifying-glass-tilted-left',
		'magnifying-glass-tilted-right',
		'candle',
		'light-bulb',
		'flashlight',
		'red-paper-lantern',
		'diya-lamp',
		'notebook-with-decorative-cover',
		'closed-book',
		'open-book',
		'green-book',
		'blue-book',
		'orange-book',
		'books',
		'notebook',
		'ledger',
		'page-with-curl',
		'scroll',
		'page-facing-up',
		'newspaper',
		'rolled-up-newspaper',
		'bookmark-tabs',
		'bookmark',
		'label',
		'money-bag',
		'yen-banknote',
		'dollar-banknote',
		'euro-banknote',
		'pound-banknote',
		'money-with-wings',
		'credit-card',
		'receipt',
		'chart-increasing-with-yen',
		'envelope',
		'e-mail',
		'incoming-envelope',
		'envelope-with-arrow',
		'outbox-tray',
		'inbox-tray',
		'package',
		'closed-mailbox-with-raised-flag',
		'closed-mailbox-with-lowered-flag',
		'open-mailbox-with-raised-flag',
		'open-mailbox-with-lowered-flag',
		'postbox',
		'ballot-box-with-ballot',
		'pencil',
		'black-nib',
		'fountain-pen',
		'pen',
		'paintbrush',
		'crayon',
		'memo',
		'briefcase',
		'file-folder',
		'open-file-folder',
		'card-index-dividers',
		'calendar',
		'tear-off-calendar',
		'spiral-notepad',
		'spiral-calendar',
		'card-index',
		'chart-increasing',
		'chart-decreasing',
		'bar-chart',
		'clipboard',
		'pushpin',
		'round-pushpin',
		'paperclip',
		'linked-paperclips',
		'straight-ruler',
		'triangular-ruler',
		'scissors',
		'card-file-box',
		'file-cabinet',
		'wastebasket',
		'locked',
		'unlocked',
		'locked-with-pen',
		'locked-with-key',
		'key',
		'old-key',
		'hammer',
		'axe',
		'pick',
		'hammer-and-pick',
		'hammer-and-wrench',
		'dagger',
		'crossed-swords',
		'water-pistol',
		'bow-and-arrow',
		'shield',
		'wrench',
		'nut-and-bolt',
		'gear',
		'clamp',
		'balance-scale',
		'white-cane',
		'link',
		'chains',
		'toolbox',
		'magnet',
		'alembic',
		'test-tube',
		'petri-dish',
		'dna',
		'microscope',
		'telescope',
		'satellite-antenna',
		'syringe',
		'drop-of-blood',
		'pill',
		'adhesive-bandage',
		'stethoscope',
		'door',
		'bed',
		'couch-and-lamp',
		'chair',
		'toilet',
		'shower',
		'bathtub',
		'razor',
		'lotion-bottle',
		'safety-pin',
		'broom',
		'basket',
		'roll-of-paper',
		'soap',
		'sponge',
		'fire-extinguisher',
		'shopping-cart',
		'cigarette',
		'coffin',
		'funeral-urn',
		'moai',
	],
	'🐢': [
		'monkey-face',
		'monkey',
		'gorilla',
		'orangutan',
		'dog-face',
		'dog',
		'guide-dog',
		'service-dog',
		'poodle',
		'wolf',
		'fox',
		'raccoon',
		'cat-face',
		'cat',
		'lion',
		'tiger-face',
		'tiger',
		'leopard',
		'horse-face',
		'horse',
		'unicorn',
		'zebra',
		'deer',
		'cow-face',
		'ox',
		'water-buffalo',
		'cow',
		'pig-face',
		'pig',
		'boar',
		'pig-nose',
		'ram',
		'ewe',
		'goat',
		'camel',
		'two-hump-camel',
		'llama',
		'giraffe',
		'elephant',
		'rhinoceros',
		'hippopotamus',
		'mouse-face',
		'mouse',
		'rat',
		'hamster',
		'rabbit-face',
		'rabbit',
		'chipmunk',
		'hedgehog',
		'bat',
		'bear',
		'koala',
		'panda',
		'sloth',
		'otter',
		'skunk',
		'kangaroo',
		'badger',
		'paw-prints',
		'turkey',
		'chicken',
		'rooster',
		'hatching-chick',
		'baby-chick',
		'front-facing-baby-chick',
		'bird',
		'penguin',
		'dove',
		'eagle',
		'duck',
		'swan',
		'owl',
		'flamingo',
		'peacock',
		'parrot',
		'frog',
		'crocodile',
		'turtle',
		'lizard',
		'snake',
		'dragon-face',
		'dragon',
		'sauropod',
		'T-Rex',
		'spouting-whale',
		'whale',
		'dolphin',
		'tropical-fish',
		'blowfish',
		'shark',
		'octopus',
		'spiral-shell',
		'snail',
		'butterfly',
		'bug',
		'ant',
		'honeybee',
		'lady-beetle',
		'cricket',
		'spider',
		'spider-web',
		'scorpion',
		'mosquito',
		'microbe',
		'bouquet',
		'cherry-blossom',
		'white-flower',
		'rosette',
		'rose',
		'wilted-flower',
		'hibiscus',
		'sunflower',
		'blossom',
		'tulip',
		'seedling',
		'evergreen-tree',
		'deciduous-tree',
		'palm-tree',
		'cactus',
		'sheaf-of-rice',
		'herb',
		'shamrock',
		'four-leaf-clover',
		'maple-leaf',
		'fallen-leaf',
		'leaf-fluttering-in-wind',
		'new-moon',
		'waxing-crescent-moon',
		'first-quarter-moon',
		'waxing-gibbous-moon',
		'full-moon',
		'waning-gibbous-moon',
		'last-quarter-moon',
		'waning-crescent-moon',
		'crescent-moon',
		'new-moon-face',
		'first-quarter-moon-face',
		'last-quarter-moon-face',
		'thermometer',
		'sun',
		'full-moon-face',
		'sun-with-face',
		'ringed-planet',
		'star',
		'glowing-star',
		'shooting-star',
		'milky-way',
		'cloud',
		'sun-behind-cloud',
		'cloud-with-lightning-and-rain',
		'sun-behind-small-cloud',
		'sun-behind-large-cloud',
		'sun-behind-rain-cloud',
		'cloud-with-rain',
		'cloud-with-snow',
		'cloud-with-lightning',
		'tornado',
		'fog',
		'wind-face',
		'cyclone',
		'rainbow',
		'closed-umbrella',
		'umbrella',
		'umbrella-with-rain-drops',
		'umbrella-on-ground',
		'high-voltage',
		'snowflake',
		'snowman',
		'snowman-without-snow',
		'comet',
		'fire',
		'droplet',
		'water-wave',
	],
	activities: [
		'jack-o-lantern',
		'Christmas-tree',
		'fireworks',
		'sparkler',
		'firecracker',
		'sparkles',
		'balloon',
		'party-popper',
		'confetti-ball',
		'tanabata-tree',
		'pine-decoration',
		'Japanese-dolls',
		'carp-streamer',
		'wind-chime',
		'moon-viewing-ceremony',
		'red-envelope',
		'ribbon',
		'wrapped-gift',
		'reminder-ribbon',
		'admission-tickets',
		'ticket',
		'military-medal',
		'trophy',
		'sports-medal',
		'1st-place-medal',
		'2nd-place-medal',
		'3rd-place-medal',
		'soccer-ball',
		'baseball',
		'softball',
		'basketball',
		'volleyball',
		'american-football',
		'rugby-football',
		'tennis',
		'flying-disc',
		'bowling',
		'cricket-game',
		'field-hockey',
		'ice-hockey',
		'lacrosse',
		'ping-pong',
		'badminton',
		'boxing-glove',
		'martial-arts-uniform',
		'goal-net',
		'flag-in-hole',
		'ice-skate',
		'fishing-pole',
		'diving-mask',
		'running-shirt',
		'skis',
		'sled',
		'curling-stone',
		'bullseye',
		'yo-yo',
		'kite',
		'pool-8-ball',
		'crystal-ball',
		'nazar-amulet',
		'video-game',
		'joystick',
		'slot-machine',
		'game-die',
		'puzzle-piece',
		'teddy-bear',
		'spade-suit',
		'heart-suit',
		'diamond-suit',
		'club-suit',
		'chess-pawn',
		'joker',
		'mahjong-red-dragon',
		'flower-playing-cards',
		'performing-arts',
		'framed-picture',
		'artist-palette',
		'thread',
		'yarn',
	],
	symbols: [
		'heart-with-arrow',
		'heart-with-ribbon',
		'sparkling-heart',
		'growing-heart',
		'beating-heart',
		'revolving-hearts',
		'two-hearts',
		'heart-decoration',
		'heart-exclamation',
		'broken-heart',
		'red-heart',
		'orange-heart',
		'yellow-heart',
		'green-heart',
		'blue-heart',
		'purple-heart',
		'brown-heart',
		'black-heart',
		'white-heart',
		'ATM-sign',
		'litter-in-bin-sign',
		'potable-water',
		'wheelchair-symbol',
		'men’s-room',
		'women’s-room',
		'restroom',
		'baby-symbol',
		'water-closet',
		'passport-control',
		'customs',
		'baggage-claim',
		'left-luggage',
		'warning',
		'children-crossing',
		'no-entry',
		'prohibited',
		'no-bicycles',
		'no-smoking',
		'no-littering',
		'non-potable-water',
		'no-pedestrians',
		'no-mobile-phones',
		'no-one-under-eighteen',
		'radioactive',
		'biohazard',
		'up-arrow',
		'up-right-arrow',
		'right-arrow',
		'down-right-arrow',
		'down-arrow',
		'down-left-arrow',
		'left-arrow',
		'up-left-arrow',
		'up-down-arrow',
		'left-right-arrow',
		'right-arrow-curving-left',
		'left-arrow-curving-right',
		'right-arrow-curving-up',
		'right-arrow-curving-down',
		'clockwise-vertical-arrows',
		'counterclockwise-arrows-button',
		'BACK-arrow',
		'END-arrow',
		'ON!-arrow',
		'SOON-arrow',
		'TOP-arrow',
		'place-of-worship',
		'atom-symbol',
		'om',
		'star-of-David',
		'wheel-of-dharma',
		'yin-yang',
		'latin-cross',
		'orthodox-cross',
		'star-and-crescent',
		'peace-symbol',
		'menorah',
		'dotted-six-pointed-star',
		'Aries',
		'Taurus',
		'Gemini',
		'Cancer',
		'Leo',
		'Virgo',
		'Libra',
		'Scorpio',
		'Sagittarius',
		'Capricorn',
		'Aquarius',
		'Pisces',
		'Ophiuchus',
		'shuffle-tracks-button',
		'repeat-button',
		'repeat-single-button',
		'play-button',
		'fast-forward-button',
		'next-track-button',
		'play-or-pause-button',
		'reverse-button',
		'fast-reverse-button',
		'last-track-button',
		'upwards-button',
		'fast-up-button',
		'downwards-button',
		'fast-down-button',
		'pause-button',
		'stop-button',
		'record-button',
		'eject-button',
		'cinema',
		'dim-button',
		'bright-button',
		'antenna-bars',
		'vibration-mode',
		'mobile-phone-off',
		'female-sign',
		'male-sign',
		'transgender-symbol',
		'multiply',
		'plus',
		'minus',
		'divide',
		'heavy-equals-sign',
		'infinity',
		'double-exclamation-mark',
		'exclamation-question-mark',
		'red-question-mark',
		'white-question-mark',
		'white-exclamation-mark',
		'red-exclamation-mark',
		'wavy-dash',
		'currency-exchange',
		'heavy-dollar-sign',
		'medical-symbol',
		'recycling-symbol',
		'fleur-de-lis',
		'trident-emblem',
		'name-badge',
		'Japanese-symbol-for-beginner',
		'hollow-red-circle',
		'check-mark-button',
		'check-box-with-check',
		'check-mark',
		'cross-mark',
		'cross-mark-button',
		'curly-loop',
		'double-curly-loop',
		'part-alternation-mark',
		'eight-spoked-asterisk',
		'eight-pointed-star',
		'sparkle',
		'copyright',
		'registered',
		'trade-mark',
		'keycap-#',
		'keycap-*',
		'keycap-0',
		'keycap-1',
		'keycap-2',
		'keycap-3',
		'keycap-4',
		'keycap-5',
		'keycap-6',
		'keycap-7',
		'keycap-8',
		'keycap-9',
		'keycap-10',
		'input-latin-uppercase',
		'input-latin-lowercase',
		'input-numbers',
		'input-symbols',
		'input-latin-letters',
		'A-button-(blood-type)',
		'AB-button-(blood-type)',
		'B-button-(blood-type)',
		'CL-button',
		'COOL-button',
		'FREE-button',
		'information',
		'ID-button',
		'circled-M',
		'NEW-button',
		'NG-button',
		'O-button-(blood-type)',
		'OK-button',
		'P-button',
		'SOS-button',
		'UP!-button',
		'VS-button',
		'Japanese-“here”-button',
		'Japanese-“service-charge”-button',
		'Japanese-“monthly-amount”-button',
		'Japanese-“not-free-of-charge”-button',
		'Japanese-“reserved”-button',
		'Japanese-“bargain”-button',
		'Japanese-“discount”-button',
		'Japanese-“free-of-charge”-button',
		'Japanese-“prohibited”-button',
		'Japanese-“acceptable”-button',
		'Japanese-“application”-button',
		'Japanese-“passing-grade”-button',
		'Japanese-“vacancy”-button',
		'Japanese-“congratulations”-button',
		'Japanese-“secret”-button',
		'Japanese-“open-for-business”-button',
		'Japanese-“no-vacancy”-button',
		'red-circle',
		'orange-circle',
		'yellow-circle',
		'green-circle',
		'blue-circle',
		'purple-circle',
		'brown-circle',
		'black-circle',
		'white-circle',
		'red-square',
		'orange-square',
		'yellow-square',
		'green-square',
		'blue-square',
		'purple-square',
		'brown-square',
		'black-large-square',
		'white-large-square',
		'black-medium-square',
		'white-medium-square',
		'black-medium-small-square',
		'white-medium-small-square',
		'black-small-square',
		'white-small-square',
		'large-orange-diamond',
		'large-blue-diamond',
		'small-orange-diamond',
		'small-blue-diamond',
		'red-triangle-pointed-up',
		'red-triangle-pointed-down',
		'diamond-with-a-dot',
		'radio-button',
		'white-square-button',
		'black-square-button',
		'regional-indicator-symbol-letter-a',
		'regional-indicator-symbol-letter-b',
		'regional-indicator-symbol-letter-c',
		'regional-indicator-symbol-letter-d',
		'regional-indicator-symbol-letter-e',
		'regional-indicator-symbol-letter-f',
		'regional-indicator-symbol-letter-g',
		'regional-indicator-symbol-letter-h',
		'regional-indicator-symbol-letter-i',
		'regional-indicator-symbol-letter-j',
		'regional-indicator-symbol-letter-k',
		'regional-indicator-symbol-letter-l',
		'regional-indicator-symbol-letter-m',
		'regional-indicator-symbol-letter-n',
		'regional-indicator-symbol-letter-o',
		'regional-indicator-symbol-letter-p',
		'regional-indicator-symbol-letter-q',
		'regional-indicator-symbol-letter-r',
		'regional-indicator-symbol-letter-s',
		'regional-indicator-symbol-letter-t',
		'regional-indicator-symbol-letter-u',
		'regional-indicator-symbol-letter-v',
		'regional-indicator-symbol-letter-w',
		'regional-indicator-symbol-letter-x',
		'regional-indicator-symbol-letter-y',
		'regional-indicator-symbol-letter-z',
	],
	'💩': [
		'grinning-face',
		'grinning-face-with-big-eyes',
		'grinning-face-with-smiling-eyes',
		'beaming-face-with-smiling-eyes',
		'grinning-squinting-face',
		'grinning-face-with-sweat',
		'rolling-on-the-floor-laughing',
		'face-with-tears-of-joy',
		'slightly-smiling-face',
		'upside-down-face',
		'winking-face',
		'smiling-face-with-smiling-eyes',
		'smiling-face-with-halo',
		'smiling-face-with-hearts',
		'smiling-face-with-heart-eyes',
		'star-struck',
		'face-blowing-a-kiss',
		'kissing-face',
		'kissing-face-with-closed-eyes',
		'kissing-face-with-smiling-eyes',
		'face-savoring-food',
		'face-with-tongue',
		'winking-face-with-tongue',
		'zany-face',
		'squinting-face-with-tongue',
		'money-mouth-face',
		'smiling-face-with-open-hands',
		'face-with-hand-over-mouth',
		'shushing-face',
		'thinking-face',
		'zipper-mouth-face',
		'face-with-raised-eyebrow',
		'neutral-face',
		'expressionless-face',
		'face-without-mouth',
		'smirking-face',
		'unamused-face',
		'face-with-rolling-eyes',
		'grimacing-face',
		'lying-face',
		'relieved-face',
		'pensive-face',
		'sleepy-face',
		'drooling-face',
		'sleeping-face',
		'face-with-medical-mask',
		'face-with-thermometer',
		'face-with-head-bandage',
		'nauseated-face',
		'face-vomiting',
		'sneezing-face',
		'hot-face',
		'cold-face',
		'woozy-face',
		'face-with-crossed-out-eyes',
		'exploding-head',
		'cowboy-hat-face',
		'partying-face',
		'smiling-face-with-sunglasses',
		'nerd-face',
		'face-with-monocle',
		'confused-face',
		'worried-face',
		'slightly-frowning-face',
		'frowning-face',
		'face-with-open-mouth',
		'hushed-face',
		'astonished-face',
		'flushed-face',
		'pleading-face',
		'frowning-face-with-open-mouth',
		'anguished-face',
		'fearful-face',
		'anxious-face-with-sweat',
		'sad-but-relieved-face',
		'crying-face',
		'loudly-crying-face',
		'face-screaming-in-fear',
		'confounded-face',
		'persevering-face',
		'disappointed-face',
		'downcast-face-with-sweat',
		'weary-face',
		'tired-face',
		'yawning-face',
		'face-with-steam-from-nose',
		'pouting-face',
		'angry-face',
		'face-with-symbols-on-mouth',
		'smiling-face-with-horns',
		'angry-face-with-horns',
		'skull',
		'skull-and-crossbones',
		'pile-of-poo',
		'clown-face',
		'ogre',
		'goblin',
		'ghost',
		'alien',
		'alien-monster',
		'robot',
		'grinning-cat',
		'grinning-cat-with-smiling-eyes',
		'cat-with-tears-of-joy',
		'smiling-cat-with-heart-eyes',
		'cat-with-wry-smile',
		'kissing-cat',
		'weary-cat',
		'crying-cat',
		'pouting-cat',
		'see-no-evil-monkey',
		'hear-no-evil-monkey',
		'speak-no-evil-monkey',
		'kiss-mark',
		'love-letter',
		'hundred-points',
		'anger-symbol',
		'collision',
		'dizzy',
		'sweat-droplets',
		'dashing-away',
		'hole',
		'bomb',
		'speech-balloon',
		'eye-in-speech-bubble',
		'left-speech-bubble',
		'right-anger-bubble',
		'thought-balloon',
		'zzz',
		'waving-hand_',
		'raised-back-of-hand_',
		'hand-with-fingers-splayed_',
		'raised-hand_',
		'vulcan-salute_',
		'OK-hand_',
		'pinching-hand_',
		'victory-hand_',
		'crossed-fingers_',
		'love-you-gesture_',
		'sign-of-the-horns_',
		'call-me-hand_',
		'backhand-index-pointing-left_',
		'backhand-index-pointing-right_',
		'backhand-index-pointing-up_',
		'middle-finger_',
		'backhand-index-pointing-down_',
		'index-pointing-up_',
		'thumbs-up_',
		'thumbs-down_',
		'raised-fist_',
		'oncoming-fist_',
		'left-facing-fist_',
		'right-facing-fist_',
		'clapping-hands_',
		'raising-hands_',
		'open-hands_',
		'palms-up-together_',
		'handshake_',
		'folded-hands_',
		'writing-hand_',
		'nail-polish_',
		'selfie_',
		'flexed-biceps_',
		'mechanical-arm',
		'mechanical-leg',
		'leg_',
		'foot_',
		'ear_',
		'ear-with-hearing-aid_',
		'nose_',
		'brain',
		'tooth',
		'bone',
		'eyes',
		'eye',
		'tongue',
		'mouth',
		'baby_',
		'child_',
		'boy_',
		'girl_',
		'person_',
		'person-blond-hair',
		'man_',
		'person-beard',
		'man-red-hair_',
		'man-curly-hair_',
		'man-white-hair_',
		'man-bald_',
		'woman_',
		'woman-red-hair_',
		'woman-curly-hair_',
		'woman-white-hair_',
		'woman-bald_',
		'woman-blond-hair_',
		'man-blond-hair_',
		'older-person_',
		'old-man_',
		'old-woman_',
		'person-frowning_',
		'man-frowning_',
		'woman-frowning_',
		'person-pouting_',
		'man-pouting_',
		'woman-pouting_',
		'person-gesturing-NO_',
		'man-gesturing-NO_',
		'woman-gesturing-NO_',
		'person-gesturing-OK_',
		'man-gesturing-OK_',
		'woman-gesturing-OK_',
		'person-tipping-hand_',
		'man-tipping-hand_',
		'woman-tipping-hand_',
		'person-raising-hand_',
		'man-raising-hand_',
		'woman-raising-hand_',
		'deaf-person_',
		'deaf-man_',
		'deaf-woman_',
		'person-bowing_',
		'man-bowing_',
		'woman-bowing_',
		'person-facepalming_',
		'man-facepalming_',
		'woman-facepalming_',
		'person-shrugging_',
		'man-shrugging_',
		'woman-shrugging_',
		'man-health-worker_',
		'woman-health-worker_',
		'man-student_',
		'woman-student_',
		'man-teacher_',
		'woman-teacher_',
		'man-judge_',
		'woman-judge_',
		'man-farmer_',
		'woman-farmer_',
		'man-cook_',
		'woman-cook_',
		'man-mechanic_',
		'woman-mechanic_',
		'man-factory-worker_',
		'woman-factory-worker_',
		'man-office-worker_',
		'woman-office-worker_',
		'man-scientist_',
		'woman-scientist_',
		'man-technologist_',
		'woman-technologist_',
		'man-singer_',
		'woman-singer_',
		'man-artist_',
		'woman-artist_',
		'man-pilot_',
		'woman-pilot_',
		'man-astronaut_',
		'woman-astronaut_',
		'man-firefighter_',
		'woman-firefighter_',
		'police-officer_',
		'man-police-officer_',
		'woman-police-officer_',
		'detective_',
		'man-detective_',
		'woman-detective_',
		'guard_',
		'man-guard_',
		'woman-guard_',
		'construction-worker_',
		'man-construction-worker_',
		'woman-construction-worker_',
		'prince_',
		'princess_',
		'person-wearing-turban_',
		'man-wearing-turban_',
		'woman-wearing-turban_',
		'person-with-skullcap_',
		'woman-with-headscarf_',
		'person-in-tuxedo_',
		'man-in-tuxedo_',
		'woman-in-tuxedo_',
		'person-with-veil_',
		'pregnant-woman_',
		'breast-feeding_',
		'baby-angel_',
		'Santa-Claus_',
		'Mrs.-Claus_',
		'superhero_',
		'man-superhero_',
		'woman-superhero_',
		'supervillain_',
		'man-supervillain_',
		'woman-supervillain_',
		'mage_',
		'man-mage_',
		'woman-mage_',
		'fairy_',
		'man-fairy_',
		'woman-fairy_',
		'vampire_',
		'man-vampire_',
		'woman-vampire_',
		'merperson_',
		'merman_',
		'mermaid_',
		'elf_',
		'man-elf_',
		'woman-elf_',
		'genie',
		'man-genie',
		'woman-genie',
		'zombie',
		'man-zombie',
		'woman-zombie',
		'person-getting-massage_',
		'man-getting-massage_',
		'woman-getting-massage_',
		'person-getting-haircut_',
		'man-getting-haircut_',
		'woman-getting-haircut_',
		'person-walking_',
		'man-walking_',
		'woman-walking_',
		'person-standing_',
		'man-standing_',
		'woman-standing_',
		'person-kneeling_',
		'man-kneeling_',
		'woman-kneeling_',
		'man-with-white-cane_',
		'woman-with-white-cane_',
		'man-in-motorized-wheelchair_',
		'woman-in-motorized-wheelchair_',
		'man-in-manual-wheelchair_',
		'woman-in-manual-wheelchair_',
		'person-running_',
		'man-running_',
		'woman-running_',
		'woman-dancing_',
		'man-dancing_',
		'person-in-suit-levitating_',
		'people-with-bunny-ears_',
		'men-with-bunny-ears_',
		'women-with-bunny-ears_',
		'person-in-steamy-room_',
		'man-in-steamy-room_',
		'woman-in-steamy-room_',
		'person-climbing_',
		'man-climbing_',
		'woman-climbing_',
		'person-fencing',
		'horse-racing_',
		'skier_',
		'snowboarder_',
		'person-golfing_',
		'man-golfing_',
		'woman-golfing_',
		'person-surfing_',
		'man-surfing_',
		'woman-surfing_',
		'person-rowing-boat_',
		'man-rowing-boat_',
		'woman-rowing-boat_',
		'person-swimming_',
		'man-swimming_',
		'woman-swimming_',
		'person-bouncing-ball_',
		'man-bouncing-ball_',
		'woman-bouncing-ball_',
		'person-lifting-weights_',
		'man-lifting-weights_',
		'woman-lifting-weights_',
		'person-biking_',
		'man-biking_',
		'woman-biking_',
		'person-mountain-biking_',
		'man-mountain-biking_',
		'woman-mountain-biking_',
		'person-cartwheeling_',
		'man-cartwheeling_',
		'woman-cartwheeling_',
		'people-wrestling_',
		'men-wrestling_',
		'women-wrestling_',
		'person-playing-water-polo_',
		'man-playing-water-polo_',
		'woman-playing-water-polo_',
		'person-playing-handball_',
		'man-playing-handball_',
		'woman-playing-handball_',
		'person-juggling_',
		'man-juggling_',
		'woman-juggling_',
		'person-in-lotus-position_',
		'man-in-lotus-position_',
		'woman-in-lotus-position_',
		'person-taking-bath_',
		'person-in-bed_',
		'people-holding-hands_',
		'women-holding-hands_',
		'woman-and-man-holding-hands',
		'men-holding-hands_',
		'kiss',
		'kiss-woman,-man',
		'kiss-man,-man',
		'kiss-woman,-woman',
		'couple-with-heart',
		'couple-with-heart-woman,-man',
		'couple-with-heart-man,-man',
		'couple-with-heart-woman,-woman',
		'family',
		'family-man,-woman,-boy',
		'family-man,-woman,-girl',
		'family-man,-woman,-girl,-boy',
		'family-man,-woman,-boy,-boy',
		'family-man,-woman,-girl,-girl',
		'family-man,-man,-boy',
		'family-man,-man,-girl',
		'family-man,-man,-girl,-boy',
		'family-man,-man,-boy,-boy',
		'family-man,-man,-girl,-girl',
		'family-woman,-woman,-boy',
		'family-woman,-woman,-girl',
		'family-woman,-woman,-girl,-boy',
		'family-woman,-woman,-boy,-boy',
		'family-woman,-woman,-girl,-girl',
		'family-man,-boy',
		'family-man,-boy,-boy',
		'family-man,-girl',
		'family-man,-girl,-boy',
		'family-man,-girl,-girl',
		'family-woman,-boy',
		'family-woman,-boy,-boy',
		'family-woman,-girl',
		'family-woman,-girl,-boy',
		'family-woman,-girl,-girl',
		'speaking-head',
		'bust-in-silhouette',
		'busts-in-silhouette',
		'footprints',
	],
	flags: [
		'flag-afghanistan',
		'flag-albania',
		'flag-algeria',
		'flag-american-samoa',
		'flag-andorra',
		'flag-angola',
		'flag-anguilla',
		'flag-antarctica',
		'flag-antigua-barbuda',
		'flag-argentina',
		'flag-armenia',
		'flag-aruba',
		'flag-ascension-island',
		'flag-australia',
		'flag-austria',
		'flag-azerbaijan',
		'flag-bahamas',
		'flag-bahrain',
		'flag-bangladesh',
		'flag-barbados',
		'flag-belarus',
		'flag-belgium',
		'flag-belize',
		'flag-benin',
		'flag-bermuda',
		'flag-bhutan',
		'flag-bolivia',
		'flag-bosnia-herzegovina',
		'flag-botswana',
		'flag-bouvet-island',
		'flag-brazil',
		'flag-british-indian-ocean-territory',
		'flag-british-virgin-islands',
		'flag-brunei',
		'flag-bulgaria',
		'flag-burkina-faso',
		'flag-burundi',
		'flag-c-te-d-ivoire',
		'flag-cambodia',
		'flag-cameroon',
		'flag-canada',
		'flag-canary-islands',
		'flag-cape-verde',
		'flag-caribbean-netherlands',
		'flag-cayman-islands',
		'flag-central-african-republic',
		'flag-ceuta-melilla',
		'flag-chad',
		'flag-chile',
		'flag-china',
		'flag-christmas-island',
		'flag-clipperton-island',
		'flag-cocos-keeling-islands',
		'flag-colombia',
		'flag-comoros',
		'flag-congo-brazzaville',
		'flag-congo-kinshasa',
		'flag-cook-islands',
		'flag-costa-rica',
		'flag-croatia',
		'flag-cuba',
		'flag-cura-ao',
		'flag-cyprus',
		'flag-czechia',
		'flag-denmark',
		'flag-diego-garcia',
		'flag-djibouti',
		'flag-dominica',
		'flag-dominican-republic',
		'flag-ecuador',
		'flag-egypt',
		'flag-el-salvador',
		'flag-england',
		'flag-equatorial-guinea',
		'flag-eritrea',
		'flag-estonia',
		'flag-eswatini',
		'flag-ethiopia',
		'flag-european-union',
		'flag-falkland-islands',
		'flag-faroe-islands',
		'flag-fiji',
		'flag-finland',
		'flag-france',
		'flag-french-guiana',
		'flag-french-polynesia',
		'flag-french-southern-territories',
		'flag-gabon',
		'flag-gambia',
		'flag-georgia',
		'flag-germany',
		'flag-ghana',
		'flag-gibraltar',
		'flag-greece',
		'flag-greenland',
		'flag-grenada',
		'flag-guadeloupe',
		'flag-guam',
		'flag-guatemala',
		'flag-guernsey',
		'flag-guinea',
		'flag-guinea-bissau',
		'flag-guyana',
		'flag-haiti',
		'flag-heard-mcdonald-islands',
		'flag-honduras',
		'flag-hong-kong-sar-china',
		'flag-hungary',
		'flag-iceland',
		'flag-in-hole',
		'flag-india',
		'flag-indonesia',
		'flag-iran',
		'flag-iraq',
		'flag-ireland',
		'flag-isle-of-man',
		'flag-israel',
		'flag-italy',
		'flag-jamaica',
		'flag-japan',
		'flag-jersey',
		'flag-jordan',
		'flag-kazakhstan',
		'flag-kenya',
		'flag-kiribati',
		'flag-kosovo',
		'flag-kuwait',
		'flag-kyrgyzstan',
		'flag-land-islands',
		'flag-laos',
		'flag-latvia',
		'flag-lebanon',
		'flag-lesotho',
		'flag-liberia',
		'flag-libya',
		'flag-liechtenstein',
		'flag-lithuania',
		'flag-luxembourg',
		'flag-macao-sar-china',
		'flag-madagascar',
		'flag-malawi',
		'flag-malaysia',
		'flag-maldives',
		'flag-mali',
		'flag-malta',
		'flag-marshall-islands',
		'flag-martinique',
		'flag-mauritania',
		'flag-mauritius',
		'flag-mayotte',
		'flag-mexico',
		'flag-micronesia',
		'flag-moldova',
		'flag-monaco',
		'flag-mongolia',
		'flag-montenegro',
		'flag-montserrat',
		'flag-morocco',
		'flag-mozambique',
		'flag-myanmar-burma',
		'flag-namibia',
		'flag-nauru',
		'flag-nepal',
		'flag-netherlands',
		'flag-new-caledonia',
		'flag-new-zealand',
		'flag-nicaragua',
		'flag-niger',
		'flag-nigeria',
		'flag-niue',
		'flag-norfolk-island',
		'flag-north-korea',
		'flag-north-macedonia',
		'flag-northern-mariana-islands',
		'flag-norway',
		'flag-oman',
		'flag-pakistan',
		'flag-palau',
		'flag-palestinian-territories',
		'flag-panama',
		'flag-papua-new-guinea',
		'flag-paraguay',
		'flag-peru',
		'flag-philippines',
		'flag-pitcairn-islands',
		'flag-poland',
		'flag-portugal',
		'flag-puerto-rico',
		'flag-qatar',
		'flag-r-union',
		'flag-romania',
		'flag-russia',
		'flag-rwanda',
		'flag-s-o-tom-pr-ncipe',
		'flag-samoa',
		'flag-san-marino',
		'flag-saudi-arabia',
		'flag-scotland',
		'flag-senegal',
		'flag-serbia',
		'flag-seychelles',
		'flag-sierra-leone',
		'flag-singapore',
		'flag-sint-maarten',
		'flag-slovakia',
		'flag-slovenia',
		'flag-solomon-islands',
		'flag-somalia',
		'flag-south-africa',
		'flag-south-georgia-south-sandwich-islands',
		'flag-south-korea',
		'flag-south-sudan',
		'flag-spain',
		'flag-sri-lanka',
		'flag-st-barth-lemy',
		'flag-st-helena',
		'flag-st-kitts-nevis',
		'flag-st-lucia',
		'flag-st-martin',
		'flag-st-pierre-miquelon',
		'flag-st-vincent-grenadines',
		'flag-sudan',
		'flag-suriname',
		'flag-svalbard-jan-mayen',
		'flag-sweden',
		'flag-switzerland',
		'flag-syria',
		'flag-taiwan',
		'flag-tajikistan',
		'flag-tanzania',
		'flag-thailand',
		'flag-timor-leste',
		'flag-togo',
		'flag-tokelau',
		'flag-tonga',
		'flag-trinidad-tobago',
		'flag-tristan-da-cunha',
		'flag-tunisia',
		'flag-turkey',
		'flag-turkmenistan',
		'flag-turks-caicos-islands',
		'flag-tuvalu',
		'flag-u-s-outlying-islands',
		'flag-u-s-virgin-islands',
		'flag-uganda',
		'flag-ukraine',
		'flag-united-arab-emirates',
		'flag-united-kingdom',
		'flag-united-nations',
		'flag-united-states',
		'flag-uruguay',
		'flag-uzbekistan',
		'flag-vanuatu',
		'flag-vatican-city',
		'flag-venezuela',
		'flag-vietnam',
		'flag-wales',
		'flag-wallis-futuna',
		'flag-western-sahara',
		'flag-yemen',
		'flag-zambia',
		'flag-zimbabwe',
		'black-flag',
		'chequered-flag',
		'crossed-flags',
		'white-flag',
		'transgender-flag',
		'triangular-flag',
		'rainbow-flag',
		'pirate-flag',
	],
};
